spring:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置
  datasource: #?????
    url: jdbc:mysql://127.0.0.1:3306/forum_db?characterEncoding=utf8&useSSL=false
    username: root
    password: '123456'
    driver-class-name: com.mysql.cj.jdbc.Driver
  application:
    name: ???? #????
  output:
    ansi:
      enabled: ALWAYS #??????????
server:
  port: 8081
logging:
  pattern:
    dateformat: MM-dd HH:mm:ss #??????
  level:
    root: info #????
    com.lxy.forum: debug #????????
  file:
    name: spring.log


# mybatis 相关配置
mybatis:
  mapper-locations: classpath:mapper/**/*.xml

mvc:
  pathmatch:
   matching-strategy: ANT_PATH_MATCHER #Springfox-Swagger兼容性配置

